on:
  schedule:
    - cron: '30 5 * * 0'
  push:
    paths:
      - '**.Rmd'
      - '**.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-renv@v2

      - name: Render Rmarkdown files
        run: |
          RMD_PATH=($(find . -name "*.Rmd"))
          echo $RMD_PATH
          Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) rmarkdown::render(f)' ${RMD_PATH[*]} 

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add "*.png" || echo "No png files to add"
          git add "*.md" || echo "No markdown files to add"
          git commit -m 'Re-build GitHub metrics' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
